### ISSUE TITLE
Document recommended usage of .toObject()

### ISSUE THREAD

**Issue by DanielSWolf** [rbuckton/QueryJS#5]
`Query.toObject()` expects as first argument the prototype for the newly-created object. I'm pretty proficient in JavaScript, but prototypes have never become second nature to me.

Usually, what I want is just a plain object, as if I had created it via `{ ... }`. It would be great if the documentation gave an example of this most likely case. That way, I wouldn't have to wonder each time: Do I pass `Object`? `Object.prototype`? `{}`? `null`? (No, probably not `null`.)

**Comment by rbuckton** [comment]
I've added [additional documentation](https://rbuckton.github.io/iterable-query/classes/_iterable_query_.query.html#toobject) and a minor API update to make this easier.

Fixed in aebf92701cec30e6fdf2016709d6f75b74eaad8d
Published as `iterable-query@1.0.0-pre.13`

**Comment by DanielSWolf** [comment]
Thanks!
